[Gmail]
source = maildir://~/mail
outgoing = /usr/sbin/sendmail
# default       = INBOX
from          = Igor Maurício <igor.mauricio.eng@gmail.com>
cache-headers = true
copy-to = Sent

[Contato]
source = maildir://~/mail/hostinger
outgoing = /usr/sbin/sendmail
from = Igor Maurício <your@domain.com>
copy-to = Sent
default = INBOX
cache-headers = true

# [Hotmail]
# source = maildirpp://~/mail/hotmail
# outgoing = /usr/sbin/sendmail
# from = Igor Maurício <igor_mcampos@hotmail.com>
# cache-headers = true
# copy-to = Sent Items

# [Hotmail]
# source = maildirpp://~/mail/hotmail
# outgoing = /usr/sbin/sendmail
# from = Igor Maurício <igor_mcampos@hotmail.com>
# cache-headers = true
# copy-to = Sent Items

